name: Invitation to the GitHub Community Organization
description: I would like to be part of the awesome community!
title: "Please invite me to the GitHub Community Organization"
labels: inviteme
assignees: devarshishimpi
body:
  - type: input
    id: name
    attributes:
      label: Name
      placeholder: Insert your name here
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        Feel free to check out other cool repositories of the DVS Tech Community [here](https://github.com/dvstechlabs)