on:
  issues:
    types: [labeled]

jobs:
  automate_invite:
    runs-on: ubuntu-latest
    steps:
      - name: Invite on label
        uses: vj-abigo/invite-on-label@v1.3
        with:
          organization: dvstechlabs
          label: invite me to the organization
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          comment: 'Welcome to the DVS Tech Labs, Invitation sent to join the GitHub Organisation. Also Don''t forget after accepting to make it public so it appears on your GitHub profile for everyone else to see. You can do this by finding your name in the GitHub organisation list and change the dropdown to public here https://github.com/orgs/dvstechlabs/people 🎉'
        env:
          INVITE_TOKEN: ${{ secrets.INVITE_TOKEN }}